name: Child Action

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Child Action
        uses: DibyajyotiMishra/GitActionsCommon/.github/workflows/common.yaml@main